pipeline {
    agent any
    tools {
        // This MUST match the name in your Global Tool Configuration exactly
        maven 'MAVEN 3' 
    }
    stages {
        stage('Build') {
            steps {
                // Use 'bat' for Windows, 'sh' for Linux
                bat 'mvn clean package'
            }
        }
    }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }

